name: Cabbage
version: ${project.version}
main: main.java.Main
api-version: 1.13

commands:
  'cabbage join':
    description: "Allows a player to join a team"
    usage: /cabbage join
    aliases: ['cabbage team']